"""
Medical assistant chatbot — placeholder Retrieval-Augmented Generation (RAG) pipeline.

Exposes the three stages of a standard RAG flow as separate, independently
replaceable functions:

    retrieve_context(question, prediction_context) -> list[str]
    build_prompt(question, context, prediction_context) -> str
    generate_answer(prompt) -> str

The service layer (`app/services/chatbot_service.py`) orchestrates these three
calls in order. Swapping the vector store, the retriever, or the underlying
LLM only requires editing this file.
"""
import logging
from typing import Optional

logger = logging.getLogger(__name__)

model_version = "placeholder-v0"

# TODO(AI engineer): replace with a real knowledge base, e.g. a vector store
# (FAISS/Chroma/pgvector) built over medical literature, clinical guidelines,
# or disease-specific fact sheets.
_PLACEHOLDER_KNOWLEDGE_BASE = [
    "Breast ultrasound BI-RADS categories range from 0 (incomplete) to 6 (known malignancy).",
    "Malignant lesions on ultrasound often show irregular margins and taller-than-wide shape.",
    "AI-assisted diagnosis tools are intended to support, not replace, a qualified clinician's judgment.",
]


def retrieve_context(question: str, prediction_context: Optional[dict] = None) -> list[str]:
    """
    Retrieve the most relevant knowledge snippets for the given question.

    TODO(AI engineer): replace with real retrieval, e.g.:
        query_embedding = embed(question)
        results = vector_store.similarity_search(query_embedding, k=5)
        return [r.text for r in results]
    """
    logger.info("Retrieving placeholder context for question: %.50s...", question)
    context = list(_PLACEHOLDER_KNOWLEDGE_BASE)
    if prediction_context:
        context.append(
            f"Relevant prior prediction: disease={prediction_context.get('disease')}, "
            f"label={prediction_context.get('predicted_label')}, "
            f"confidence={prediction_context.get('confidence')}."
        )
    return context


def build_prompt(question: str, context: list[str], prediction_context: Optional[dict] = None) -> str:
    """
    Assemble the final prompt sent to the generative model from the
    question and retrieved context.

    TODO(AI engineer): tune this template, add system instructions, safety
    guardrails, and citation formatting as needed.
    """
    context_block = "\n".join(f"- {c}" for c in context)
    return (
        "You are a clinical decision-support assistant. Use the context below "
        "to answer the clinician's question. Always recommend confirming with "
        "a qualified specialist for final diagnosis.\n\n"
        f"Context:\n{context_block}\n\n"
        f"Question: {question}\n"
        "Answer:"
    )


def generate_answer(prompt: str) -> str:
    """
    Generate the final natural-language answer from the assembled prompt.

    TODO(AI engineer): replace with a real call to an LLM, e.g. the
    Anthropic API, a local fine-tuned medical LLM, or an internal service:

        response = anthropic_client.messages.create(
            model="claude-...", max_tokens=1000,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text
    """
    logger.info("Generating placeholder chatbot answer")
    return (
        "[Placeholder answer] This response is generated by a stub RAG pipeline. "
        "Connect a real LLM in `generate_answer()` to produce clinically grounded answers. "
        "Always verify AI-assisted output with a qualified medical professional."
    )
